import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";


export function downloadReport(report) {
  const doc = new jsPDF();

  doc.setFontSize(22);
  doc.text("AI Health Companion", 14, 20);

  doc.setFontSize(16);
  doc.text("Health Summary Report", 14, 32);

  doc.setDrawColor(220);
  doc.line(14, 36, 196, 36);

  // Health Score
  doc.setFontSize(14);
  doc.text("Health Score", 14, 48);
  doc.setFontSize(24);
 doc.text(`${report?.healthScore ?? 0} / 100`, 14, 60);

  // AI Summary
  doc.setFontSize(14);
  doc.text("AI Summary", 14, 78);

  doc.setFontSize(11);

  doc.text(
    "Most parameters are within the normal range. Vitamin D is low, TSH is borderline and LDL Cholesterol requires attention.",
    14,
    88,
    {
      maxWidth: 180,
    },
  );

  // Needs Attention
  doc.setFontSize(14);
  doc.text("Needs Attention", 14, 112);

  doc.setFontSize(11);

  doc.text("• Vitamin D", 18, 122);
  doc.text("• TSH", 18, 130);
  doc.text("• LDL Cholesterol", 18, 138);

  // Table
  autoTable(doc, {
    startY: 150,
    head: [["Test", "Status", "Value", "Reference"]],
    body: tests.map((test) => [test.name, test.status, test.value, test.range]),
    styles: {
      fontSize: 10,
    },
    headStyles: {
      fillColor: [14, 165, 233],
    },
  });

  const pageHeight = doc.internal.pageSize.height;

  doc.setDrawColor(220);
  doc.line(14, pageHeight - 22, 196, pageHeight - 22);

  doc.setFontSize(9);
  doc.setTextColor(120);

  doc.text("Generated by AI Health Companion", 14, pageHeight - 14);

  doc.text(
    "This summary is AI-generated and intended for informational purposes only. It does not replace professional medical advice.",
    14,
    pageHeight - 8,
    {
      maxWidth: 180,
    },
  );

  doc.save("Health-Summary.pdf");
}
